name: brian-sim
channels:
- conda-forge
- defaults
dependencies:
- cycler=0.10.0=py36_0
- cython=0.25.2=py36_1
- dbus=1.10.10=3
- expat=2.1.0=2
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- glib=2.51.4=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- icu=58.1=1
- jpeg=9b=0
- libffi=3.2.1=3
- libiconv=1.14=4
- libpng=1.6.28=0
- libxcb=1.12=1
- libxml2=2.9.4=4
- matplotlib=2.0.0=np112py36_3
- pcre=8.39=0
- py-cpuinfo=0.2.3=py36_1
- pyqt=5.6.0=py36_1
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- qt=5.6.2=1
- sip=4.18=py36_1
- six=1.10.0=py36_1
- tornado=4.4.3=py36_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- jinja2=2.9.6=py36_0
- markupsafe=0.23=py36_2
- mkl=2017.0.1=0
- mpmath=0.19=py36_1
- numpy=1.12.1=py36_0
- openssl=1.0.2k=1
- pip=9.0.1=py36_1
- pyparsing=2.1.4=py36_0
- python=3.6.1=0
- readline=6.2=2
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- sympy=1.0=py36_0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3

